### ISSUE TITLE
Request for Adding New Programming Models - Kokkos and RAJA 

### ISSUE THREAD

**Issue by pranav-sivaraman** [ANL-CESAR/RSBench#19]
Our research group is currently doing research on parallel programming models and are interested in contributing to the RSBench project by adding new models such as Kokkos and RAJA.

As part of the plan, we propose restructuring the project to follow a similar structure as [BabelStream](https://github.com/UoB-HPC/BabelStream), which would allow for better organization and maintainability. 

We would like to know if there are any current plans within the RSBench project regarding the addition of these models We are eager to contribute to the project by implementing these products. 

Any feedback, suggestions, or guidance on this proposal would be highly appreciated. We are looking forward to collaborating with the RSBench community to further improve this valuable benchmarking tool.

Thank you for considering our request.

**Comment by jtramm** [comment]
Hi @pranav-sivaraman -- thanks for reaching out about this! 

> adding new models such as Kokkos and RAJA

Yes, addition of Kokkos and RAJA versions would be welcome. I have long been thinking of adding in these models, but have not yet had the time, so this is great! If you're interested, adding them to XSBench would be useful as well. 

>As part of the plan, we propose restructuring the project to follow a similar structure as [BabelStream](https://github.com/UoB-HPC/BabelStream), which would allow for better organization and maintainability.

I can definitely see how restructuring and using CMake would have certain benefits, but I'm worried there may be a lot of downsides as well:

- In particular, CMake is not nearly as ubiquitous as Make, and even where available I've found that it is often an outdated version that doesn't support the newer CMake features builds usually rely on. While it is usually available, in the past year alone I've had to manually compile CMake on several different systems, so I don't want to force every user of RSBench to do this. As RSBench currently has no dependencies at all, I think adding in a new dependency is not worthwhile. 
- Unlike BabelStream, people are commonly hacking in new features to XSBench and RSBench for the purposes of testing a new library or MC cross section lookup technique. These sorts of developers are usually just interested in using a single specific programming model, so it is of great importance that the code be generally readable and editable by being written as if it were a native application to that programming model. While BabelStream's organization makes life easy for the user who is just compiling and running the code, the BabelStream repo structure and source code itself is somewhat bloated with templates and obfuscating abstractions that make it a lot harder to actually read or edit. This works well for BabelStream as people are not usually reading or editing the source, but this is not true of XS/RSBench. A such, I think the current "fully siloed" style makes life a lot easier for developers, even if it has other downsides.
- I also think that the current Makefile setup makes it really easy to manually edit compiler flags, and to transparently see what compiler flags are going to be used, whereas this is usually more of a pain to do in CMake. 

With that said, I think for the Kokkos/RAJA versions, it would be acceptable for those builds to use CMake in a siloed manner (provided all CMake files etc are contained without their programming models' source folders, and that CMake is not required at all for the project as a whole). My thinking is that RAJA and Kokkos are massive dependencies in their own right, so anyone who has jumped through all the hoops to install them almost certainly has already installed CMake (or is capable of compiling it from source themselves without emailing for help). I can also understand if all the dependencies needed for the Kokkos/RAJA models are more easily handled in CMake. However, if it's as simple as just adding in a `-lkokkos -L/.../ -I/.../` or something to the makefile, then maybe that is a better route.

**Comment by pranav-sivaraman** [comment]
Thanks for the response @jtramm. Just wanted to make some more comments based on the feedback your provided.

I do agree that CMake is not always available and that sometimes that the version that is installed may be very old. Looking at the Kokkos and RAJA projects there are simple examples that show how to use the libraries in Makefiles. 

One thing I liked about the BabelStream structure was having a base abstract class for the benchmark and have each model implementation inherit that base class. This would definitely reduce the amount of code duplication in the repository. However, I think this contradicts the idea that developers would want to have each model implementation as their own working directory.

Finally I was just curious on why RSBench has their own complex number type defined. Is it because you wanted to use the `fast_exp()` function? Would it make sense to transition to using `std::complex` or the complex number type in `complex.h` and  avoid the all the copies performed in the defined `c_add(), c_sub()` etc.

To add onto this how important is that we preserve backwards compatibility with the other models. RAJA requires C++14 features. For the new models can I make more usage of the C++ standard library such as using `std::cout` and etc. I probably would not go super far and use templates in the new model implementations. 

Thanks 
Pranav Sivaraman

**Comment by jtramm** [comment]
>One thing I liked about the BabelStream structure was having a base abstract class for the benchmark and have each model implementation inherit that base class. This would definitely reduce the amount of code duplication in the repository. 

One issue here is that RSBench uses C instead of C++ (at least for the OpenMP and OpenCL versions). I've found over the years that using C instead of C++ has a number of advantages. Namely, I have run on several experimental hardware simulators where only rudimentary C compilers are provided, and no C++ compilers exist, so I don't like the idea of losing that flexibility just for minor code organization improvements. Also, OpenCL kernel code is not going to support templates or classes, so there is not really a way of having everything be C++ anyway.

> why RSBench has their own complex number type defined.

We actually originally used the `complex.h` types, but ran into portability issues as this is a C99 feature that is not particularly well supported (particularly when running on barebones C compilers for experimental hardware simulators). `std::complex` is of course well supported by C++ compilers, but again, I don't think it would be good to use C++ for programming models that it's not required for. So, for the sake of universal portability, we just define our own complex number functions.

>To add onto this how important is that we preserve backwards compatibility with the other models. RAJA requires C++14 features. For the new models can I make more usage of the C++ standard library such as using std::cout and etc. I probably would not go super far and use templates in the new model implementations.

What is meant by backwards compatibility?

I'd say that the new models should:
- Produce the same verification checksums for the preset problem sizes
- Support the same input arguments (though addition of a few new ones to e.g. control which device ID to run on, or how many threads per block to use, etc are fine).
- Have generally the same layout of functions and naming conventions where feasible, though minor differences are ok. Idea is that someone familiar with the CPU codebase should be able to find the equivalent routine in another code base very quickly.

Generally use of a different C++ standard is totally fine -- similarly I think the SYCL model requires C++17. It is definitely fine for each siloed model to use whatever makes sense for that model. Use of the C++ STL for higher level models is also fine, as being able to compile Kokkos/RAJA implies the existence of a good C++ compiler and STL implementation on that system.
